### PR TITLE
FixBugLogoutNextcloudFromCas =)

### PR DESCRIPTION
**Pull request by pingou2712**
Fix bug : Difference between:
-> logout CAS session if logout Nextcloud session
And:
-> logout Nextcloud session if logout CAS session

For language i update l10n/fr ( l10n/fr.js , l10n/fr.json) , i don't know what i must do...

I have an another perso patch for group naming because your code don't do what i want... tell me if you are interested ;)
Bye

### CODE REVIEW

**Comment by alexisberindei** [comment]
It's working well !
Need some more tests but for now well done 👍

**Comment by pingou2712** [comment]
thank you ;)
I'm happy to help!

**Comment by felixrupp** [comment]
@pingou2712 I implemented your callback function into the code, without the other unnecessary changes. Please see [Release 1.8.3](https://github.com/felixrupp/user_cas/releases/tag/1.8.3).

Thank you for your input!

**Comment by pingou2712** [comment]
You continue to confuse two very different things:
-> logout of the CAS session if there is logout of the Owncloud session (some people want this option)
-> logout of the Owncloud session if there is logout of the CAS session (few people want this option)
It's two very different options.
The code that you get out of my patch was not unnecessary, please think carefully about this question.
Please, tell me if you don't change your mind because this would force me to make another personal patch.

**Comment by felixrupp** [comment]
Hi @pingou2712 

You‘re right. My current approach was, as always, based on what is given (configured) by the CAS server. So, if you don‘t want SingleSignout, just disable it in your CAS server instance.
If you disable the CAS logout in user_cas in general (and only terminate the ownCloud session), a SingleSignout makes no sense in my opinion. 

But if it helps you, I will add another checkbox option to enable/disable both features seperately tomorrow. 


Regards,
Felix

**Comment by alexisberindei** [comment]
Indeed it's not what we want ahah.
I'll try again asap.

Thank you @pingou2712 !

**Comment by pingou2712** [comment]
@alexisberindei 
Ok Done. Last version https://github.com/felixrupp/user_cas/pull/87 :P The previous version don't remove connection of smartphone... So not good... I made a job for clean up.

**Pull request closed without merging**
